### ISSUE TITLE
Malformed input can cause excessive memory allocation

### ISSUE THREAD

**Issue by M2Ys4U** [zaethan/opus_headers#5]
Hi there,

I ran a fuzzer on this crate and it managed to uncover an out-of-memory crash.

From a very quick look at the code, it seems that `read_byte_vec` [pre-allocates a vector](https://github.com/zaethan/opus_headers/blob/008640c1b5a844518f03b767135c5ee367b94308/src/read_ext.rs#L67) with a size that is extracted verbatim from the input file (at least [here](https://github.com/zaethan/opus_headers/blob/008640c1b5a844518f03b767135c5ee367b94308/src/opus_header_structs.rs#L96) and [here](https://github.com/zaethan/opus_headers/blob/008640c1b5a844518f03b767135c5ee367b94308/src/opus_header_structs.rs#L104) - these are in the function that the fuzzer tripped on) allowing an attacker to craft an opus file that will exhaust the machine's memory, or otherwise cause excessive allocation.

I've attached the minimal test case (zipped because GitHub doesn't allow opus attachments to issues) produced by rust-fuzz, hope that helps.

Cheers

[minimized-from-7bdc9f5196cea729c07f16f484685efc51ae4034.zip](https://github.com/zaethan/opus_headers/files/5133450/minimized-from-7bdc9f5196cea729c07f16f484685efc51ae4034.zip)

**Comment by yboettcher** [comment]
Thank you very much for taking the time to find and report this.
May I ask how you did the actual fuzzing? I found [cargo fuzz](https://github.com/rust-fuzz/cargo-fuzz) and just ran it with `cargo fuzz run name_of_target`. As far as I can tell, it "just" throws a lot of random bytes at the library it is testing.

It _should_ be fixed it now. I now keep track of the length of the comment header and reject it, if it exceeds 120MB. This is mentioned in the specification as a countermeasure against such attacks.
While parsing the strings, I now check whether the strings length exceeds the remaining header and, if it does, abort parsing. This way the maximum memory allocation consists of a little more than 120MB for the Ogg pages and another 120MB for the parsed header, totaling 240MB.

**Comment by M2Ys4U** [comment]
> May I ask how you did the actual fuzzing? I found cargo fuzz and just ran it with cargo fuzz run name_of_target. As far as I can tell, it "just" throws a lot of random bytes at the library it is testing.

libFuzzer - the underlying library used by cargo-fuzz - [allows one to seed the fuzzer with examples](https://llvm.org/docs/LibFuzzer.html#running), it'll then make randomised changes to the input.

I added the `silence_standard.opus` file provided in your test directory in the repo to the `corpus/fuzz_target_1` directory in the fuzz harness and the fuzzer used that as a starting point.

**Comment by yboettcher** [comment]
Thanks for the explanation :)
(and sorry for the late reply)

I also just noticed that I totally forgot about pushing my fix to github... anyway, since I can run the tests with the file you provided without running out of memory (and it returns the expected error) I would assume this to be fixed.
Thanks for your help.
